### ISSUE TITLE
Wrong path for Upgrading LDAP Replica Servers or Multi-Master Server

### ISSUE THREAD

**Issue by mogsdad** [Zimbra/installguides#38]
From a [forum post](https://forums.zimbra.org/viewtopic.php?t=65924#p289376) by Zimbra partner "pup_sepa":

> Documentation ... is still providing a wrong path for ldif files. 
> 
> Proposed path in documentation is `/opt/zimbra/openldap/etc/openldap/schema/zimbra.ldif`, which does not exists. Instead, i used this `/opt/zimbra/common/etc/openldap/zimbra/schema/zimbra.ldif`

**Comment by abyshukla** [comment]
commit # c4e22dd354fe68c1585dd357782d5deadcb1e480
